//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6.ServicioSoapTarea {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int PuntajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSoapTarea.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento st del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        ConsoleApplication6.ServicioSoapTarea.insertarResponse insertar(ConsoleApplication6.ServicioSoapTarea.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.insertarResponse> insertarAsync(ConsoleApplication6.ServicioSoapTarea.insertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        ConsoleApplication6.ServicioSoapTarea.buscarResponse buscar(ConsoleApplication6.ServicioSoapTarea.buscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.buscarResponse> buscarAsync(ConsoleApplication6.ServicioSoapTarea.buscarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPuntaje", ReplyAction="*")]
        ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse actualizarPuntaje(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPuntaje", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse> actualizarPuntajeAsync(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificar", ReplyAction="*")]
        ConsoleApplication6.ServicioSoapTarea.verificarResponse verificar(ConsoleApplication6.ServicioSoapTarea.verificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.verificarResponse> verificarAsync(ConsoleApplication6.ServicioSoapTarea.verificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse HelloWorld(ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse> HelloWorldAsync(ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertar", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.insertarRequestBody Body;
        
        public insertarRequest() {
        }
        
        public insertarRequest(ConsoleApplication6.ServicioSoapTarea.insertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string st;
        
        public insertarRequestBody() {
        }
        
        public insertarRequestBody(string st) {
            this.st = st;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.insertarResponseBody Body;
        
        public insertarResponse() {
        }
        
        public insertarResponse(ConsoleApplication6.ServicioSoapTarea.insertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertarResult;
        
        public insertarResponseBody() {
        }
        
        public insertarResponseBody(int insertarResult) {
            this.insertarResult = insertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscar", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.buscarRequestBody Body;
        
        public buscarRequest() {
        }
        
        public buscarRequest(ConsoleApplication6.ServicioSoapTarea.buscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public buscarRequestBody() {
        }
        
        public buscarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.buscarResponseBody Body;
        
        public buscarResponse() {
        }
        
        public buscarResponse(ConsoleApplication6.ServicioSoapTarea.buscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool buscarResult;
        
        public buscarResponseBody() {
        }
        
        public buscarResponseBody(bool buscarResult) {
            this.buscarResult = buscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPuntajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPuntaje", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequestBody Body;
        
        public actualizarPuntajeRequest() {
        }
        
        public actualizarPuntajeRequest(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarPuntajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int puntaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        public actualizarPuntajeRequestBody() {
        }
        
        public actualizarPuntajeRequestBody(int puntaje, string nombre) {
            this.puntaje = puntaje;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarPuntajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarPuntajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponseBody Body;
        
        public actualizarPuntajeResponse() {
        }
        
        public actualizarPuntajeResponse(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class actualizarPuntajeResponseBody {
        
        public actualizarPuntajeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificar", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.verificarRequestBody Body;
        
        public verificarRequest() {
        }
        
        public verificarRequest(ConsoleApplication6.ServicioSoapTarea.verificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public verificarRequestBody() {
        }
        
        public verificarRequestBody(string nombre, string password) {
            this.nombre = nombre;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.verificarResponseBody Body;
        
        public verificarResponse() {
        }
        
        public verificarResponse(ConsoleApplication6.ServicioSoapTarea.verificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.Jugador verificarResult;
        
        public verificarResponseBody() {
        }
        
        public verificarResponseBody(ConsoleApplication6.ServicioSoapTarea.Jugador verificarResult) {
            this.verificarResult = verificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApplication6.ServicioSoapTarea.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication6.ServicioSoapTarea.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApplication6.ServicioSoapTarea.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApplication6.ServicioSoapTarea.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApplication6.ServicioSoapTarea.WebService1Soap>, ConsoleApplication6.ServicioSoapTarea.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication6.ServicioSoapTarea.insertarResponse ConsoleApplication6.ServicioSoapTarea.WebService1Soap.insertar(ConsoleApplication6.ServicioSoapTarea.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(string st) {
            ConsoleApplication6.ServicioSoapTarea.insertarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.insertarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.insertarRequestBody();
            inValue.Body.st = st;
            ConsoleApplication6.ServicioSoapTarea.insertarResponse retVal = ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).insertar(inValue);
            return retVal.Body.insertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.insertarResponse> ConsoleApplication6.ServicioSoapTarea.WebService1Soap.insertarAsync(ConsoleApplication6.ServicioSoapTarea.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.insertarResponse> insertarAsync(string st) {
            ConsoleApplication6.ServicioSoapTarea.insertarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.insertarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.insertarRequestBody();
            inValue.Body.st = st;
            return ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication6.ServicioSoapTarea.buscarResponse ConsoleApplication6.ServicioSoapTarea.WebService1Soap.buscar(ConsoleApplication6.ServicioSoapTarea.buscarRequest request) {
            return base.Channel.buscar(request);
        }
        
        public bool buscar(string nombre) {
            ConsoleApplication6.ServicioSoapTarea.buscarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.buscarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.buscarRequestBody();
            inValue.Body.nombre = nombre;
            ConsoleApplication6.ServicioSoapTarea.buscarResponse retVal = ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).buscar(inValue);
            return retVal.Body.buscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.buscarResponse> ConsoleApplication6.ServicioSoapTarea.WebService1Soap.buscarAsync(ConsoleApplication6.ServicioSoapTarea.buscarRequest request) {
            return base.Channel.buscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.buscarResponse> buscarAsync(string nombre) {
            ConsoleApplication6.ServicioSoapTarea.buscarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.buscarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.buscarRequestBody();
            inValue.Body.nombre = nombre;
            return ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).buscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse ConsoleApplication6.ServicioSoapTarea.WebService1Soap.actualizarPuntaje(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest request) {
            return base.Channel.actualizarPuntaje(request);
        }
        
        public void actualizarPuntaje(int puntaje, string nombre) {
            ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest inValue = new ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequestBody();
            inValue.Body.puntaje = puntaje;
            inValue.Body.nombre = nombre;
            ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse retVal = ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).actualizarPuntaje(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse> ConsoleApplication6.ServicioSoapTarea.WebService1Soap.actualizarPuntajeAsync(ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest request) {
            return base.Channel.actualizarPuntajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeResponse> actualizarPuntajeAsync(int puntaje, string nombre) {
            ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest inValue = new ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.actualizarPuntajeRequestBody();
            inValue.Body.puntaje = puntaje;
            inValue.Body.nombre = nombre;
            return ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).actualizarPuntajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication6.ServicioSoapTarea.verificarResponse ConsoleApplication6.ServicioSoapTarea.WebService1Soap.verificar(ConsoleApplication6.ServicioSoapTarea.verificarRequest request) {
            return base.Channel.verificar(request);
        }
        
        public ConsoleApplication6.ServicioSoapTarea.Jugador verificar(string nombre, string password) {
            ConsoleApplication6.ServicioSoapTarea.verificarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.verificarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.verificarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            ConsoleApplication6.ServicioSoapTarea.verificarResponse retVal = ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).verificar(inValue);
            return retVal.Body.verificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.verificarResponse> ConsoleApplication6.ServicioSoapTarea.WebService1Soap.verificarAsync(ConsoleApplication6.ServicioSoapTarea.verificarRequest request) {
            return base.Channel.verificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.verificarResponse> verificarAsync(string nombre, string password) {
            ConsoleApplication6.ServicioSoapTarea.verificarRequest inValue = new ConsoleApplication6.ServicioSoapTarea.verificarRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.verificarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            return ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).verificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse ConsoleApplication6.ServicioSoapTarea.WebService1Soap.HelloWorld(ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest inValue = new ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.HelloWorldRequestBody();
            ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse retVal = ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse> ConsoleApplication6.ServicioSoapTarea.WebService1Soap.HelloWorldAsync(ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication6.ServicioSoapTarea.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest inValue = new ConsoleApplication6.ServicioSoapTarea.HelloWorldRequest();
            inValue.Body = new ConsoleApplication6.ServicioSoapTarea.HelloWorldRequestBody();
            return ((ConsoleApplication6.ServicioSoapTarea.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
